### PR TITLE
Improved README / animated GIF

### PR DESCRIPTION
**Pull request by riccardoporreca**
General review of README

Animated GIF as outlined in #9.

@fvitalini should advise on reviewing / improving the MacOS part.

### CODE REVIEW

**Comment by fvitalini** [comment]
Meld is not yet officially supported for macOs ( reference http://meldmerge.org )
OS X builds are provided on the meld website. Additionally, Meld is available from MacPorts, Fink or Brew, but according to the meld website none of these methods are supported.

**Comment by fvitalini** [comment]
As a personal comment, in the gif it is unclear how the conflicts are resolved. Maybe a couple of more frames? Also a final screenshot that clearly marks the end of the gif before it restarts would be nice.

**Comment by riccardoporreca** [comment]
@fvitalini 
> As a personal comment, in the gif it is unclear how the conflicts are resolved. Maybe a couple of more frames? Also a final screenshot that clearly marks the end of the gif before it restarts would be nice.

The GIF currently does not show the resolution of the conflict but only how to get to the Meld merge view. The focus is not really to show how to resolve this specific conflict but how you get to a tool / view you can use to resolve conflicts.

Showing the final resolved status was the idea of the final step mentioned in #9. However this final step cannot be recorded live in one go, since the conflict resolution is manual and maybe not easy / worth showing in a GIF demo (it would be quite a few more frames). We could try to transition to a screenshot showing the final resolution if it helps.

As for the restart, a blurred version of the last screenshot with a reload "wheel" might help.

**Comment by fvitalini** [comment]
The new version of the gif is nicer and more informative.

**Comment by riccardoporreca** [comment]
> [...] it makes sense to remove them and point to the Meld website https://wiki.gnome.org/Apps/Meld/OSX

I actually checked and that wiki is pretty outdated (2015-01-21), so I am not including the link in the reviewed MacOs part in 1067a40.

**Comment by riccardoporreca** [comment]
Note that `Title` and `Description` in the DESCRIPTION file have also been updated in c7187b1.

**Comment by riccardoporreca** [comment]
Upon merge into `master` (shortly after this pull request to `develop`), we probably want to align the repo description
image
to the new title in README title (RStudio Diff / Merge Addins with VCS Capabilities)

**Pull request merged**
